### ISSUE TITLE
Anfrage Gehäuse

### ISSUE THREAD

**Issue by hanneskh1002** [klein0r/pcb-cc26x2r1-hat#1]
Gibt es ein fertiges Geäuse für dieses Projekt? Also eine .stl Datei für einen 3D Drucker?
Ich dachte mal irgendwo etwas gesehen zu haben, bin im Netz jedoch nicht fündig geworden.

**Comment by klein0r** [comment]
Hier z.B.

https://www.thingiverse.com/thing:5281550

Aber ich hab keine Variante erstellt, wo die Adapter-Platine hier rein passt.
Habe das auch nicht mehr im Einsatz. Gibt ja jetzt fertige Lösungen von cod.m und SMLight
